include $(TOPDIR)/rules.mk

APP_TITLE := API endpint for getting information about connected devices and their dhcp info
CLOSED_GPL_INSTALL := y

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature